services:
  bot:
    image: bot
    build:
      context: .
    container_name: bot
    env_file:
      - .env
    command: bash -c "python bot.py"
    restart: on-failure:10
  server:
    image: server
    build:
      context: .
    container_name: server
    env_file:
      - .env
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    restart: on-failure:10